services:
  blog:
    # Use the appropriate image based on your server architecture:
    # For AMD64/x86_64 servers:
    image: blog-app:amd64
    # For ARM64 servers (uncomment the line below and comment out the line above):
    #image: blog-app:arm64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
